server:
  port: 8080

spring:
  application:
    name: safeshare
  data:
    mongodb:
      uri: mongodb://localhost:27017/safeshare

jwt:
  secret: c2FmZXNoYXJlLXNlY3JldC1rZXktMzJi
  expiration: 3600000  # 1 hour in milliseconds
